output "control_plane_ipv4" {
  description = "Public IPv4 of the k3s control-plane node."
  value       = module.cluster.control_plane_ipv4
}

output "agent_ipv4s" {
  description = "Public IPv4s of the k3s agent nodes."
  value       = module.cluster.agent_ipv4s
}

output "load_balancer_ipv4" {
  description = "Public IPv4 of the load balancer. Point your DNS (var.domain) here."
  value       = module.lb.ipv4
}

output "kubeconfig_path" {
  description = "Local path to the fetched k3s kubeconfig."
  value       = var.kubeconfig_path
}

output "kubeconfig_command" {
  description = "How to use the cluster after apply."
  value       = "export KUBECONFIG=${abspath(var.kubeconfig_path)} && kubectl get nodes"
}

output "next_steps" {
  description = "Post-apply guidance."
  value = var.install_apps ? join("\n", [
    "Cluster + apps applied (health-stack chart).",
    "1) Point DNS '${var.domain}' at the LB IP above.",
    "2) export KUBECONFIG=${abspath(var.kubeconfig_path)}",
    "3) Create the required Secrets out-of-band (incl. openfhir-license):",
    "     (only the openFHIR license — all other Secrets are generated by Terraform)",
    "4) kubectl get pods -n health-stack",
    "5) curl https://${var.domain}/fhir/metadata",
    ]) : join("\n", [
    "Phase 1 complete (cluster only). Now run phase 2:",
    "  terraform apply    # installs add-ons + the health-stack chart",
  ])
}

# ── Generated credentials ─────────────────────────────────────────────────────
# Retrieve with:
#   terraform output -json credentials | jq
#   terraform output -raw ehrbase_api_password        # single value, unquoted
#
# ⚠ These live in terraform.tfstate in plaintext. Keep that file private
#   (it is gitignored + chmod 600); anyone who can read it has every password.
output "credentials" {
  description = "All generated service credentials."
  sensitive   = true
  value = {
    postgres_superuser   = random_password.pg_superuser.result
    ehrbase_db           = random_password.ehrbase_db.result
    ehrbase_db_admin     = random_password.ehrbase_db_admin.result
    hapi_db              = random_password.hapi_db.result
    openfhir_db          = random_password.openfhir_db.result
    ehrbase_api_user     = "ehrbase-user"
    ehrbase_api_password = random_password.ehrbase_api.result
  }
}

# The one you need most often: EHRbase's REST basic-auth (used by `make template`
# and any direct /ehrbase call).
output "ehrbase_api_password" {
  description = "Basic-auth password for the EHRbase REST API."
  sensitive   = true
  value       = random_password.ehrbase_api.result
}
