output "control_plane_ipv4" {
  description = "Public IPv4 of the k3s control-plane node."
  value       = module.cluster.control_plane_ipv4
}

output "agent_ipv4s" {
  description = "Public IPv4s of the k3s agent nodes."
  value       = module.cluster.agent_ipv4s
}

output "load_balancer_ipv4" {
  description = "Public IPv4 of the load balancer. Point your DNS (var.domain) here."
  value       = module.lb.ipv4
}

output "kubeconfig_path" {
  description = "Local path to the fetched k3s kubeconfig."
  value       = var.kubeconfig_path
}

output "kubeconfig_command" {
  description = "How to use the cluster after apply."
  value       = "export KUBECONFIG=${abspath(var.kubeconfig_path)} && kubectl get nodes"
}

output "next_steps" {
  description = "Post-apply guidance."
  value = var.install_apps ? join("\n", [
    "Cluster + apps applied (health-stack chart).",
    "1) Point DNS '${var.domain}' at the LB IP above.",
    "2) export KUBECONFIG=${abspath(var.kubeconfig_path)}",
    "3) Create the required Secrets out-of-band (incl. openfhir-license):",
    "     (only the openFHIR license — all other Secrets are generated by Terraform)",
    "4) kubectl get pods -n health-stack",
    "5) TOKEN=$(curl -sX POST https://${var.domain}/auth/realms/freshehr/protocol/openid-connect/token -d grant_type=client_credentials -d client_id=api-client -d client_secret=$(terraform output -raw kc_api_client_secret) | sed -n 's/.*\"access_token\":\"\\([^\"]*\\)\".*/\\1/p')",
    "6) curl -H \"Authorization: Bearer $TOKEN\" https://${var.domain}/fhir/metadata",
    ]) : join("\n", [
    "Phase 1 complete (cluster only). Now run phase 2:",
    "  terraform apply    # installs add-ons + the health-stack chart",
  ])
}

# ── Generated credentials ─────────────────────────────────────────────────────
# Retrieve with:
#   terraform output -json credentials | jq
#   terraform output -raw kc_api_client_secret        # single value, unquoted
#
# ⚠ These live in terraform.tfstate in plaintext. Keep that file private
#   (it is gitignored + chmod 600); anyone who can read it has every password.
output "credentials" {
  description = "All generated service credentials."
  sensitive   = true
  value = {
    postgres_superuser            = random_password.pg_superuser.result
    ehrbase_db                    = random_password.ehrbase_db.result
    ehrbase_db_admin              = random_password.ehrbase_db_admin.result
    hapi_db                       = random_password.hapi_db.result
    openfhir_db                   = random_password.openfhir_db.result
    keycloak_db                   = random_password.keycloak_db.result
    keycloak_admin_user           = "admin"
    keycloak_admin_password       = random_password.keycloak_admin.result
    kc_api_client_id              = "api-client"
    kc_api_client_secret          = random_password.kc_api_client.result
    kc_hapi_svc_secret            = random_password.kc_hapi_svc.result
    kc_dokter_joost_secret        = random_password.kc_dokter_joost.result
    kc_verpleegkundige_bas_secret = random_password.kc_verpleegkundige_bas.result
    oauth2_proxy_client_secret    = random_password.oauth2_proxy_client.result
    oauth2_proxy_cookie_secret    = random_password.oauth2_proxy_cookie.result
  }
}

# The one you need most often: the client_credentials secret for external API
# calls to every route (/fhir, /ehrbase, /openfhir all take the same token).
#   curl -sX POST https://<domain>/auth/realms/freshehr/protocol/openid-connect/token \
#     -d grant_type=client_credentials -d client_id=api-client \
#     -d client_secret=$(terraform output -raw kc_api_client_secret)
output "kc_api_client_secret" {
  description = "client_credentials secret for the api-client OIDC client."
  sensitive   = true
  value       = random_password.kc_api_client.result
}

# Keycloak admin console login (https://<domain>/auth/admin/, user `admin`).
output "keycloak_admin_password" {
  description = "Keycloak admin console password."
  sensitive   = true
  value       = random_password.keycloak_admin.result
}
